development:
  url: <%= ENV['REDIS_PATH'] %>
  redis_cache:
    host: localhost
    port: "6379"
    db: "2"
    namespace: cache
    expires_in: "90"

test:
  url: <%= ENV['REDIS_TEST_PATH'] %>

staging:
  url: <%= ENV['REDIS_PATH'] %>

production:
  url: <%= ENV['REDIS_PATH'] %>